/**
 * Initializes the first lottery round after `anchor deploy`.
 *
 * Usage:
 *   npx ts-node scripts/deploy.ts
 *
 * Reads the Anchor provider (wallet + cluster) from the ANCHOR_WALLET /
 * ANCHOR_PROVIDER_URL env vars, matching the same config used by
 * `anchor deploy --provider.cluster devnet`.
 */
import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { PublicKey, LAMPORTS_PER_SOL } from "@solana/web3.js";
import fs from "fs";
import path from "path";

// The IDL is generated by `anchor build` into program/target/idl/solana_lottery.json
const IDL_PATH = path.join(__dirname, "..", "target", "idl", "solana_lottery.json");

// Devnet placeholder VRF account — replace with a real Switchboard VRF
// account created via the `sb solana vrf create` command in the README.

async function main() {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  if (!fs.existsSync(IDL_PATH)) {
    throw new Error(
      `IDL not found at ${IDL_PATH}. Run "anchor build" first, then re-run this script.`
    );
  }
  const idl = JSON.parse(fs.readFileSync(IDL_PATH, "utf-8"));
  const programId = new PublicKey(idl.address ?? idl.metadata.address);
  const program = new Program(idl as any, provider) as Program<any>;

  const authority = provider.wallet.publicKey;

  // Bump this for every new lottery round you initialize; a config account
  // that auto-increments an on-chain counter is a natural follow-up if you
  // want to avoid tracking this manually.
  const lotteryId = new anchor.BN(Date.now());
  const ticketPriceLamports = new anchor.BN(0.1 * LAMPORTS_PER_SOL);
  const maxTickets = 10;
  const durationSeconds = new anchor.BN(60 * 60); // 1 hour

  const [lotteryPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("lottery"), authority.toBuffer(), lotteryId.toArrayLike(Buffer, "le", 8)],
    programId
  );
  const [escrowPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("escrow"), lotteryPda.toBuffer()],
    programId
  );

  console.log("Program ID:   ", programId.toBase58());
  console.log("Authority:    ", authority.toBase58());
  console.log("Lottery PDA:  ", lotteryPda.toBase58());
  console.log("Escrow PDA:   ", escrowPda.toBase58());
  console.log("Ticket price: ", ticketPriceLamports.toNumber() / LAMPORTS_PER_SOL, "SOL");
  console.log("Max tickets:  ", maxTickets);

  const txSig = await (program.methods as any)
    .initializeLottery(lotteryId, ticketPriceLamports, maxTickets, durationSeconds)
    .accounts({
      authority,
      lottery: lotteryPda,
      escrow: escrowPda,
      systemProgram: anchor.web3.SystemProgram.programId,
    })
    .rpc();

  console.log("\n✅ Lottery initialized");
  console.log("Transaction: ", txSig);

  // Write the lottery address out so the frontend's config.json can pick it up.
  const configPath = path.join(__dirname, "..", "app", "src", "config.json");
  fs.writeFileSync(
    configPath,
    JSON.stringify(
      {
        programId: programId.toBase58(),
        lotteryId: lotteryId.toString(),
        lottery: lotteryPda.toBase58(),
        escrow: escrowPda.toBase58(),
      },
      null,
      2
    )
  );
  console.log("Wrote frontend config to", configPath);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
